from pathlib import Path
import json, math, hashlib
from PIL import Image, ImageDraw
R=Path(__file__).resolve().parent
read=lambda n:json.loads((R/n).read_text())
def save(n,d):(R/n).write_text(json.dumps(d,indent=2)+'\n')
b=read('room-brief.json');b.update(purpose='Premium contemporary home interior design showcase with a connected room-by-room walkthrough.',runtimeSurface='Existing React / React Three Fiber website. Review stage only.',boundsMeters=[20,18,3.4],hero={'id':'living-conversation','role':'Travertine table and tailored linen sofa facing the garden','reservedBoundsMeters':[5.5,4.5,2.8]},symmetry={'mode':'none','order':1,'appliesTo':[],'exceptions':['Asymmetric functional plan; local bed and dining compositions are balanced.']},circulation={'description':'2 m east-west gallery, 2.4 m entry, door-linked room visits; return to shared passage before moving to another room. Living opens to terrace.', 'minimumClearanceMeters':.9},productionCamera={'viewport':[1440,900],'location':[5.8,5.1,1.6],'target':[3.2,2.8,1.1],'verticalFovDegrees':55},performanceBudget={'maxSceneTriangles':450000,'maxVLowBytes':8000000,'maxHighTextureBytes':64000000},creditBudget={'maximumCredits':0,'approvalRequired':True})
b['artifacts']={'floorPlan':'plans/lower-room.png','reflectedCeilingPlan':'plans/reflected-ceiling.png','planMetadata':'plan-metadata.json','wallElevations':['plans/south-elevation.png'],'visualTarget':'review.html','openingContactSheet':'masks/contact-sheet.png'};save('room-brief.json',b)
p=read('plan-metadata.json');p['coverage']=['room-outline','cutouts','openings','exterior-apron','main-sign','ingress-props','floor-markers','barriers','columns','circulation','placed-features'];p['notApplicable']={'main-sign':'Private residence; exterior branding remains website UI.','floor-markers':'Room names in accessible web UI, not on physical floor.','barriers':'Walls define room containment.','columns':'No freestanding columns in this scheme.'};p['rooms']=read('concept-rooms.json');save('plan-metadata.json',p)
s=read('openings.json');sheet=Image.new('RGB',(1200,math.ceil(len(s['openings'])/5)*220),'white');d=ImageDraw.Draw(sheet)
for i,o in enumerate(s['openings']):
 im=Image.new('L',(160,160),0);di=ImageDraw.Draw(im);di.rectangle((16,16,143,159 if o['kind']=='door' else 143),fill=255);im.save(R/o['mask'])
 h=0 if o['kind']=='door' else 16/159
 cutter={'schema':'game-room.opening-cutter.v1','id':o['id'],'kind':o['kind'],'widthMeters':o['widthMeters'],'heightMeters':o['heightMeters'],'sillMeters':o['sillMeters'],'depthMeters':o['depthMeters'],'source':Path(o['mask']).name,'sourceSha256':hashlib.sha256((R/o['mask']).read_bytes()).hexdigest(),'imageSize':[160,160],'contours':[{'role':'outer','points':[[16/159,h],[143/159,h],[143/159,143/159],[16/159,143/159]]}],'generator':'Analytical rectangular concept mask; skill OpenCV tracing pending.'};save(o['cutter'],cutter)
 x=(i%5)*240;y=(i//5)*220;sheet.paste(im,(x+40,y+10));d.text((x+10,y+176),o['id'],fill='black');d.text((x+10,y+194),f"{o['widthMeters']} x {o['heightMeters']} m / {o['kind']}",fill='black')
sheet.save(R/'masks/contact-sheet.png')
props=read('props.json');props['generation']['note']='No paid generation proposed. Furniture concepts are authored in Blender. Meshy-only validator conditions remain unsatisfied; do not fabricate pricing or spend approval.'
assets=[('sofa','Tailored three-seat sofa',[3.8,1.05,1.03],'hero',18000),('table','Travertine pedestal coffee table',[1.4,1.4,.385],'hero',8000),('chair','Oak and upholstered dining chair',[.57,.6,1.03],'reusable',6000),('bed','Upholstered bed with oak headboard',[3.5,2.5,1.5],'hero',24000),('island','Stone waterfall kitchen island',[1.34,2.85,.98],'hero',16000),('pendant','Suspended linen pendant',[.64,.64,.92],'reusable',4000)]
props['assets']=[]
for id,desc,dims,cls,poly in assets:
 props['assets'].append({'id':id,'function':desc,'description':desc,'class':cls,'dimensionsMeters':dims,'attachmentFace':'ceiling' if id=='pendant' else 'floor','semanticFront':'negative-z' if id=='pendant' else 'negative-y','targetPolycount':poly,'intendedInstances':0,'rejectionCriteria':['Floating support or visible mesh penetration','Incorrect real-world dimensions','Faceting visible at the production camera'],'image':{'source':'images/furniture-reference.png','generator':'Blender 5.0.1 / build_concept.py','prompt':desc+'; native Blender concept geometry, authored in the home at real scale.','approved':False,'approvedBy':''}})
save('props.json',props)
v=read('milestone-reviews.json');v['function'].update(evidence=['review.html','concept.blend','plans/lower-room.png','images/furniture-reference.png','masks/contact-sheet.png'],strangestElement='The cutaway deliberately hides the ceiling; the live home must be enclosed. Large shared gallery could feel institutional unless daylight, oak reveals and arrival views soften it.',notes='Awaiting user approval of layout and direction. This is concept geometry, not the final realistic asset.');save('milestone-reviews.json',v)
f=read('final-report.json');f['postmortem']['observations']=['Existing exporter disables texture coordinates, leaving a flat material scene.','Existing camera anchors remain outside each room in the gallery.','New concept includes all major domestic functions and real cut-through openings.'];f['postmortem']['remainingRisks']=['Function approval pending.','Detailed furniture, PBR maps and baked illumination are not built.','Navigation positions are proposed; swept camera collision validation remains before runtime.','Bundled validator requires paid Meshy artifacts even for native Blender assets; those requirements remain reported, not bypassed.'];save('final-report.json',f)
rows=''.join(f"<tr><td>{r['label']}</td><td>{r['bounds'][2]-r['bounds'][0]:g} × {r['bounds'][3]-r['bounds'][1]:g} m</td><td>{'Private wing' if r['bounds'][1]>=8 else 'Garden / shared wing'}</td></tr>" for r in p['rooms'])
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Better Homes — Blender design review</title><style>*{box-sizing:border-box}body{margin:0;background:#f2efe8;color:#292922;font:16px/1.6 system-ui}main{max-width:1180px;margin:auto;padding:56px 28px}h1{font:52px/1.05 Georgia;max-width:780px;margin:20px 0}h2{font:32px Georgia;margin:48px 0 20px}small{letter-spacing:.16em;text-transform:uppercase}p{max-width:800px;color:#606054}.pill{display:inline-block;border:1px solid #aaa797;border-radius:30px;padding:5px 14px;font-size:12px}img{width:100%;display:block;border-radius:6px;background:white}figure{margin:24px 0}figcaption{font-size:13px;color:#656458;margin-top:10px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card{background:#e9e5dc;padding:22px;border-radius:6px}.swatches{display:flex;gap:12px;flex-wrap:wrap}.swatch{flex:1;min-width:120px}.swatch i{height:85px;display:block;border-radius:4px}button{padding:12px 18px;border:1px solid #777568;border-radius:30px;background:transparent;cursor:pointer}button[aria-pressed=true]{background:#343e31;color:white}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px;border-bottom:1px solid #d2cfc5}a{color:#384c32}.note{border-left:3px solid #737a59;padding:12px 20px;background:#e8e8de}@media(max-width:700px){h1{font-size:38px}.grid{grid-template-columns:1fr}}</style><main><small>Better Homes / Interior design direction 01</small><h1>A warm, modern home.<br>Rooms that belong together.</h1><span class="pill">BLENDER CONCEPT • AWAITING LAYOUT REVIEW</span><p>A complete home with generous shared spaces, a private bedroom wing and a direct connection to the garden. Oak joinery, softly textured plaster, honed stone and tailored upholstery establish the proposed palette.</p><figure><img src="renders/layout-axon.png" alt="Blender cutaway showing the proposed home layout"><figcaption>Actual Blender geometry at metre scale. Ceiling removed for layout review. Furniture, materials and planting are concept studies; this is not the finished realistic interior.</figcaption></figure><div class="grid"><div class="card"><b>Believable scale</b><p>3.1 m ceilings, a 2 m shared gallery and a generous 2.4 m arrival opening.</p></div><div class="card"><b>Enter each room</b><p>Human-height views travel through scheduled doors. Return to the gallery between rooms; camera paths must be collision-checked.</p></div><div class="card"><b>Layered realism</b><p>Next stage: measured PBR textures, fabric detail, stone variation, daylight and fixture-matched baked lighting.</p></div></div><h2>Proposed material direction</h2><div class="swatches">'''
for label,color in [('Soft plaster','#d6cfc0'),('Natural oak','#936b45'),('Honed travertine','#bba282'),('Tailored linen','#c3bba9'),('Aged bronze','#514235'),('Garden sage','#69745d')]:html+=f'<div class="swatch"><i style="background:{color}"></i>{label}</div>'
html+='''</div><h2>Review the connected plan</h2><p>North / upper row: guest bedroom, study, guest bathroom, primary bedroom, dressing and ensuite. South / lower row: living and dining, kitchen and utility. The garden terrace lies along the south facade; entry is from the west.</p><div><button aria-pressed="true" onclick="showPlan(this,'lower-room')">Furniture & circulation</button> <button aria-pressed="false" onclick="showPlan(this,'reflected-ceiling')">Ceiling fixtures</button></div><figure><img id="plan" src="plans/lower-room.png" alt="Monochrome orthographic projection of the actual Blender room geometry"><figcaption>Both layers are projections of the same Blender scene. The ceiling layer shows proposed hanging fixtures and gallery lights.</figcaption></figure><table><thead><tr><th>Space</th><th>Planning bay</th><th>Location</th></tr></thead><tbody>'''+rows+'''</tbody></table><h2>Furniture proportions</h2><figure><img src="images/furniture-reference.png" alt="Furniture concept geometry with walls hidden"><figcaption>Native Blender furniture concepts in their actual positions. These define proportions and placement for review; upholstery seams, final joinery and surface detail follow layout approval.</figcaption></figure><h2>Facade & openings</h2><img src="plans/south-elevation.png" alt="South facade elevation"><p>The living room opens directly onto the terrace. Dining and kitchen glazing face the garden.</p><details><summary>Opening schedule reference sheet</summary><img src="masks/contact-sheet.png" alt="Labeled black and white doorway and window masks"></details><h2>What happens after this review</h2><ol><li>Approve or revise the room layout and warm modern material direction.</li><li>Build detailed Blender interiors and review interior renders, including ceilings and contact details.</li><li>Export textured assets, implement connected room navigation, and verify the actual website on desktop and mobile.</li></ol><p class="note">The current website model has not been replaced. This package is a reviewable concept, not a completed photorealistic build. No paid asset generation has been used.</p><p><a href="concept.blend">Blender concept source</a> · <a href="room-brief.json">Design brief</a> · <a href="concept-rooms.json">Room and camera schedule</a></p></main><script>function showPlan(button,layer){document.getElementById('plan').src='plans/'+layer+'.png';document.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b===button?'true':'false'))}</script></html>'''
(R/'review.html').write_text(html)
