# -*- coding: utf-8 -*-
"""Build Model H-014 and export it for the web."""
import bpy, json, math, os, sys

HERE = os.path.dirname(os.path.abspath(__file__ if '__file__' in dir() else sys.argv[-1]))
for p in (HERE,):
    if p not in sys.path:
        sys.path.insert(0, p)

OUT_GLB = sys.argv[sys.argv.index('--out') + 1] if '--out' in sys.argv else '/tmp/house.glb'
OUT_JSON = os.path.splitext(OUT_GLB)[0] + '.anchors.json'

src_core = open(os.path.join(HERE, 'house_core.py')).read()
src_rooms = open(os.path.join(HERE, 'house_rooms.py')).read()
src_site = open(os.path.join(HERE, 'house_site.py')).read()
src_post = open(os.path.join(HERE, 'post.py')).read()
G = globals()
exec(compile(src_core, 'house_core.py', 'exec'), G)
exec(compile(src_rooms, 'house_rooms.py', 'exec'), G)
exec(compile(src_site, 'house_site.py', 'exec'), G)
exec(compile(src_post, 'post.py', 'exec'), G)

# ------------------------------------------------------------------ build
reset()
P = build_palette()
build_shell(P)
build_site(P)
refine_roof(P)
build_living(P)
build_dining(P)
build_kitchen(P)
build_bedroom(P)
build_patio(P)

merge_by_material()

# ------------------------------------------------------------------ camera journey
# Blender is Z-up; glTF/three is Y-up. (x, y, z)_blender -> (x, z, -y)_three
def to3(v):
    return [round(v[0], 3), round(v[2], 3), round(-v[1], 3)]

JOURNEY = [
    # id            camera position (blender)       look-at target (blender)     fov
    ('landing',   (-26.0, -25.5,  3.9), ( -3.5,  0.8, 1.8), 42),
    ('hero',      (-22.0, -21.5,  3.4), ( -8.0,  0.6, 1.8), 42),
    ('services',  (-18.6, -12.5,  2.4), (-14.0, -2.5, 1.6), 44),
    ('living',    (-14.8,  -3.75, 1.60), (-12.2,  1.9, 1.25), 50),
    ('dining',    ( -7.5,  -3.6,  1.58), ( -5.0,  1.6, 1.10), 50),
    ('kitchen',   ( -1.5,  -3.5,  1.62), (  1.0,  1.7, 1.15), 50),
    ('bedroom',   (  5.0,  -3.75, 1.58), (  6.3,  3.0, 1.05), 50),
    ('patio',     ( 12.5,  -3.6,  1.72), ( 16.6,  0.2, 1.00), 54),
    ('portfolio', ( 22.5, -13.0,  4.0), (  9.0,  0.0, 1.9), 44),
    ('stories',   ( 27.0, -22.0,  5.8), (  3.0,  0.0, 1.9), 42),
    ('estimate',  ( 12.0, -32.0,  8.0), ( -2.0,  0.0, 1.9), 40),
    ('footer',    ( -8.0, -40.0, 10.0), ( -2.0,  0.0, 1.5), 38),
]

ROOM_META = {
    'living':  dict(label='Living room', lamp=(-12.0, 1.4, 2.0)),
    'dining':  dict(label='Dining',      lamp=(-5.0, 1.5, 2.05)),
    'kitchen': dict(label='Kitchen',     lamp=(1.0, 1.55, 1.95)),
    'bedroom': dict(label='Bedroom',     lamp=(7.2, 2.2, 1.9)),
    'patio':   dict(label='Patio',      lamp=(16.4, 0.55, 0.5)),
}

# Blender's camera angle is measured across the WIDER dimension; three.js
# PerspectiveCamera.fov is vertical. Convert against a 16:9 reference frame so
# the browser reproduces the framing of the preview renders.
REF_ASPECT = 16.0 / 9.0

def fov_y(h_deg):
    half = math.radians(h_deg) / 2.0
    return round(math.degrees(2.0 * math.atan(math.tan(half) / REF_ASPECT)), 2)

anchors = {
    'units': 'meters',
    'up': 'Y',
    'note': 'Generated by build_house.py — Blender Z-up converted to three.js Y-up.',
    'journey': [
        dict(id=i, pos=to3(p), target=to3(t), fov=fov_y(f), fovBlender=f)
        for (i, p, t, f) in JOURNEY
    ],
    'rooms': [
        dict(id=k, label=v['label'], lamp=to3(v['lamp'])) for k, v in ROOM_META.items()
    ],
    'bounds': dict(min=to3((-17.0, -6.0, -0.5)), max=to3((20.5, 6.0, 3.8))),
}

# ------------------------------------------------------------------ stats
deps = bpy.context.evaluated_depsgraph_get()
tris = 0
objs = 0
for o in bpy.context.scene.objects:
    if o.type != 'MESH':
        continue
    objs += 1
    me = o.evaluated_get(deps).to_mesh()
    me.calc_loop_triangles()
    tris += len(me.loop_triangles)
    o.evaluated_get(deps).to_mesh_clear()
print('STATS objects=%d triangles=%d materials=%d' % (objs, tris, len(bpy.data.materials)))

# ------------------------------------------------------------------ export
os.makedirs(os.path.dirname(OUT_GLB), exist_ok=True)
want = dict(
    filepath=OUT_GLB,
    export_format='GLB',
    export_apply=True,
    export_yup=True,
    use_selection=False,
    export_materials='EXPORT',
    export_cameras=False,
    export_lights=False,
    export_skins=False,
    export_animations=False,
    export_morph=False,
    export_normals=True,
    export_tangents=False,
    export_texcoords=False,
    export_attributes=False,
    export_extras=False,
    export_draco_mesh_compression_enable=True,
    export_draco_mesh_compression_level=6,
    export_draco_position_quantization=13,
    export_draco_normal_quantization=9,
)
props = bpy.ops.export_scene.gltf.get_rna_type().properties.keys()
kwargs = {k: v for k, v in want.items() if k in props}
dropped = [k for k in want if k not in props]
if dropped:
    print('NOTE dropped unsupported export params:', dropped)
bpy.ops.export_scene.gltf(**kwargs)

with open(OUT_JSON, 'w') as fh:
    json.dump(anchors, fh, indent=2)

print('EXPORTED %s (%.2f MB)' % (OUT_GLB, os.path.getsize(OUT_GLB) / 1e6))
print('ANCHORS %s' % OUT_JSON)

if '--preview' in sys.argv:
    only = None
    if '--only' in sys.argv:
        only = set(sys.argv[sys.argv.index('--only') + 1].split(','))
    setup_preview_world()
    web = '--web' in sys.argv
    res = (1408, 702) if web else (960, 540)
    sub = 'web' if web else 'preview'
    render_previews(JOURNEY, os.path.join(os.path.dirname(OUT_GLB), sub),
                    res=res, only=only, web=web)
